### ISSUE TITLE
Bug: When you copy html to clipboard, then it is rendered to the screen

### ISSUE THREAD

**Issue by bywasik** [KL13NT/clippy#4] opened 2021-01-27 21:37 UTC

**Comment by KL13NT** [comment] 2021-01-28 05:07
Hi @iamkacperwasik, could you provide more info?

**Comment by KL13NT** [comment] 2021-01-28 05:12
After investigation, this is not a bug actually! 😄 
Clippy renders copied HTML by default, but when copying back it copies the original HTML. This is useful in cases such that when copying some styled markup and there are multiple entries. Makes it easier to read when the same styling is applied. I may add a settings page to choose whether you wish to render HTML or keep it as is. 

Closing this now. Thanks!

**Closed as completed by KL13NT** 2021-01-28 05:12 UTC
